float Data::accelx() {return flightData[0];}
float Data::accely() {return flightData[1];}
float Data::accelz() {return flightData[2];}
float Data::gyrox() {return flightData[3];}
float Data::gyroy() {return flightData[4];}
float Data::gyroz() {return flightData[5];}
float Data::temp() {return flightData[6];}
float Data::a() {return flightData[7];}
float Data::b() {return flightData[8];}
float Data::c() {return flightData[9];}
float Data::baralt() {return flightData[10];}
float Data::d() {return flightData[11];}
float Data::lng() {return flightData[12];}
float Data::lat() {return flightData[13];}
float Data::gpsalt() {return flightData[14];}
float Data::phs() {return flightData[15];}
float Data::cont() {return flightData[16];}
float Data::volt() {return flightData[17];}
float Data::link() {return flightData[18];}
float Data::kfx() {return flightData[19];}
float Data::kfy() {return flightData[20];}
float Data::kfz() {return flightData[21];}
float Data::kfvx() {return flightData[22];}
float Data::kfvy() {return flightData[23];}
float Data::kfvz() {return flightData[24];}
float Data::kfdrag() {return flightData[25];}
float Data::curtime() {return flightData[26];}
